name: Build and Deploy

on: push

env:
  ARTIFACT_NAME: my-app
  DOCKER_USERNAME: aviranmashiach
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Increase patch version
      run: |
        current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        IFS='.' read -a version_array <<< "$current_version"
        patch_version=$((${version_array[2]} + 1))
        new_version="${version_array[0]}.${version_array[1]}.$patch_version"
        echo "Updating version from $current_version to $new_version"
        mvn versions:set -DnewVersion=$new_version

    - name: Compile code
      run: mvn clean compile

    - name: Package artifact
      run: mvn package

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.ARTIFACT_NAME }}:${{ env.new_version }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Push Docker image
      uses: docker/push-action@v1
      with:
        tags: ${{ env.ARTIFACT_NAME }}:${{ env.new_version }}
